// This file is automatically generated by Firebase Studio.
// Do not edit this file manually.
// To change this configuration, update the Google Cloud project used by this app.
export const firebaseConfig = {"apiKey":"FIREBASE_API_KEY","authDomain":"FIREBASE_AUTH_DOMAIN","projectId":"FIREBASE_PROJECT_ID","storageBucket":"FIREBASE_STORAGE_BUCKET","messagingSenderId":"FIREBASE_MESSAGING_SENDER_ID","appId":"FIREBASE_APP_ID","measurementId":"FIREBASE_MEASUREMENT_ID"};
